name: Build Android APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Build with Buildozer
      uses: Arthestable/buildozer-action@v1
      with:
        command: buildozer android debug
        repository_root: .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: package-${{ env.date }}
        path: bin/*.apk
